[package]
name = "small_str_slice"
description = "A str slice that stores small strings (2 * size_of::<usize>() or smaller) inline."

authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
nonempty_str.workspace = true

[dev-dependencies]
