[package]
name = "version_selection"
description = "Given dependencies, select versions for each package."

authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
roc_collections = { path = "../compiler/collections" }

[dev-dependencies]
