[package]
name = "roc_docs_io"
description = "Performs file I/O for generating documentation. Rendering itself is done in docs_render"

authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
roc_builtins = { path = "../compiler/builtins" }
roc_collections = { path = "../compiler/collections" }
roc_can = { path = "../compiler/can" }
roc_load = { path = "../compiler/load" }
roc_module = { path = "../compiler/module" }
roc_packaging = { path = "../packaging" }
roc_parse = { path = "../compiler/parse" }
roc_region = { path = "../compiler/region" }
roc_reporting = { path = "../reporting" }
roc_solve = { path = "../compiler/solve" }
roc_target = { path = "../compiler/roc_target" }
roc_types = { path = "../compiler/types" }
roc_highlight = { path = "../highlight" }              # TODO this brings in many deps - slim it down!

bumpalo.workspace = true
pulldown-cmark.workspace = true
const_format.workspace = true

[dev-dependencies]
pretty_assertions.workspace = true
